root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/go-admin-server"
  cmd = "go build -o tmp/go-admin-server ./cmd/server/"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = ["."]
  include_ext = ["go", "tpl", "tmpl", "html"]

[color]
  app = ""
  build = "yellow"
  main = "green"
  runner = "cyan"
  watcher = "magenta"

[log]
  main_only = false
  time = true
